services:
  web_api:
    image: nginx
    volumes:
      - ./infra/nginx_api/nginx.conf:/tmp/nginx.conf
    environment:
      - API_SERVER_ADDR=api:9091
    command: /bin/bash -c "envsubst < /tmp/nginx.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    ports:
      - 8888:8888
    depends_on:
      - backend

  api:
    build:
      context: api
      target: builder
    # flask requires SIGINT to stop gracefully
    # (default stop signal from Compose is SIGTERM)
    stop_signal: SIGINT
    environment:
      - DASHBOARD_SERVER_PORT=9092
    volumes:
      - ./api:/src
    depends_on:
      -  mongo

  web_dashboard:
    image: nginx
    volumes:
      - ./infra/nginx_dashboard/nginx.conf:/tmp/nginx.conf
    environment:
      - DASHBOARD_SERVER_ADDR=api:9092
    command: /bin/bash -c "envsubst < /tmp/nginx.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    ports:
      - 80:80
    depends_on:
      - dashboard

  dashboard:
    build:
      context: dashboard
      target: builder
    # flask requires SIGINT to stop gracefully
    # (default stop signal from Compose is SIGTERM)
    stop_signal: SIGINT
    environment:
      - DASHBOARD_SERVER_PORT=9092
    volumes:
      - ./dashboard:/src
    depends_on:
      - mongo

  mongo:
    image: mongo